### Get all Categories`
GET http://localhost:3000/api/categories
Accept: application/json

### Create new category
POST http://127.0.0.1:3000/api/categories
Content-Type: application/json

{
  "name": "Minuman"
}

### Get category by id
GET http://127.0.0.1:3000/api/categories/4
Content-Type: application/json

### Update category by id
PUT http://localhost:3000/api/categories/2
Content-Type: application/json

{
  "name": "Makanan"
}

### Delete category by id
DELETE http://127.0.0.1:3000/api/categories/3
Accept: application/json